# Generated by Django 5.2.18 on 2026-10-08 19:49

import books.models
import books.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', books.models.ISBNField(max_length=25, unique=True, validators=[books.validators.validate_isbn])),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=100)),
                ('supplier_country', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Enter a two-letter uppercase ISO 3166-1 country code.', regex='^[A-Z]{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_usd__gt', 0)), name='book_cost_usd_positive'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='book_stock_quantity_nonnegative')],
            },
        ),
    ]
